export enum AppErrorCodes {
  GENERIC_API_ERROR = 'GENERIC_API_ERROR',
  DEFAULT_EXTERNAL_API_ERROR = 'DEFAULT_EXTERNAL_API_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  UNAVAILABLE_ORIGIN_BALANCE = 'UNAVAILABLE_ORIGIN_BALANCE',
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
  USER_LACKS_PERMISSIONS = 'USER_LACKS_PERMISSIONS',
}
