export enum DeathCause {
  ACCIDENT = 1,
  ANEMIA = 2,
  STUCK = 3,
  CLOSTRIDIOSES = 4,
  COURSE = 5,
  UNKNOWN = 6,
  TANGLED_IN_THE_FENCE = 7,
  DYSTOCIA = 8,
  WEAKNESS = 9,
  BOAR = 10,
  HEMORRHAGE = 11,
  UMBILICAL_INFECTION = 12,
  INTOXICATION = 13,
  SWINE_POX = 14,
  JAGUAR = 15,
  OTHERS = 16,
  SNAKEBITE = 17,
  PNEUMONIA = 18,
  LIGHTNING_STRIKE = 19,
  LATE_BLIGHT = 20,
  THEFT = 21,
  TETANUS = 22,
  BLOAT = 23,
  PARASITIC_GASTROENTERITIS = 24,
  VULTURE = 25,
}

export enum DeathCauseLabels {
  ACCIDENT = 'Acidente',
  ANEMIA = 'Anemia',
  BLOAT = 'Timpanismo',
  BOAR = 'Gabarro',
  CLOSTRIDIOSES = 'Clostridioses',
  COURSE = 'Curso',
  DYSTOCIA = 'Enroscado no parto',
  HEMORRHAGE = 'Hemorragia',
  INTOXICATION = 'Intoxicação',
  JAGUAR = 'Onça',
  LATE_BLIGHT = 'Requeima',
  LIGHTNING_STRIKE = 'Raio',
  OTHERS = 'Outro motivo',
  PARASITIC_GASTROENTERITIS = 'Tristeza parasitária',
  PNEUMONIA = 'Pneumonia',
  SNAKEBITE = 'Picada de cobra',
  STUCK = 'Atolado',
  SWINE_POX = 'Mela',
  TANGLED_IN_THE_FENCE = 'Enroscado na cerca',
  TETANUS = 'Tétano',
  THEFT = 'Roubo',
  UMBILICAL_INFECTION = 'Infecção umbilical',
  UNKNOWN = 'Desconhecido',
  VULTURE = 'Urubu',
  WEAKNESS = 'Fraqueza',
}
