export enum CacheKeys {
  CHAT_DRAFT = 'CHAT_DRAFT',
  USER_CONTEXT = 'USER_CONTEXT',
  OUTREACH_CONTEXT = 'OUTREACH_CONTEXT',
}

export enum EnvKeys {
  REDIS_DRAFT_TTL_SEC = 'REDIS_DRAFT_TTL_SEC',
  REDIS_USER_CONTEXT_TTL_SEC = 'REDIS_USER_CONTEXT_TTL_SEC',
}
