export enum CacheKeys {
  CHAT_DRAFT = 'CHAT_DRAFT',
  USER_CONTEXT = 'USER_CONTEXT',
  BUSINESS_CONFIG = 'BUSINESS_CONFIG',
  APPOINTMENTS = 'APPOINTMENTS',
  AVAILABLE_SLOTS = 'AVAILABLE_SLOTS',
  REMINDERS_PENDING = 'REMINDERS_PENDING',
  REMINDER_DATA = 'REMINDER_DATA',
}

export enum EnvKeys {
  REDIS_DRAFT_TTL_SEC = 'REDIS_DRAFT_TTL_SEC',
  REDIS_USER_CONTEXT_TTL_SEC = 'REDIS_USER_CONTEXT_TTL_SEC',
}
