export interface OpenAIModelConfig {
  OPENAI_AGENT_ROUTER_MODEL: string
  OPENAI_AGENT_FLOW_MODEL: string
  OPENAI_AGENT_RESPONSE_MODEL: string
  OPENAI_NLG_MODEL: string
  OPENAI_INVOICE_OCR_MODEL: string
}

export const OPENAI_MODEL_DEFAULTS: OpenAIModelConfig = {
  OPENAI_AGENT_ROUTER_MODEL: 'gpt-4.1-mini',
  OPENAI_AGENT_FLOW_MODEL: 'gpt-4.1-mini',
  OPENAI_AGENT_RESPONSE_MODEL: 'gpt-4.1-nano',
  OPENAI_NLG_MODEL: 'gpt-4.1-mini',
  OPENAI_INVOICE_OCR_MODEL: 'gpt-4o',
}

export function getOpenAIModelConfig(source: NodeJS.ProcessEnv = process.env): OpenAIModelConfig {
  return {
    OPENAI_AGENT_ROUTER_MODEL: source.OPENAI_AGENT_ROUTER_MODEL || OPENAI_MODEL_DEFAULTS.OPENAI_AGENT_ROUTER_MODEL,
    OPENAI_AGENT_FLOW_MODEL: source.OPENAI_AGENT_FLOW_MODEL || OPENAI_MODEL_DEFAULTS.OPENAI_AGENT_FLOW_MODEL,
    OPENAI_AGENT_RESPONSE_MODEL: source.OPENAI_AGENT_RESPONSE_MODEL || OPENAI_MODEL_DEFAULTS.OPENAI_AGENT_RESPONSE_MODEL,
    OPENAI_NLG_MODEL: source.OPENAI_NLG_MODEL || OPENAI_MODEL_DEFAULTS.OPENAI_NLG_MODEL,
    OPENAI_INVOICE_OCR_MODEL: source.OPENAI_INVOICE_OCR_MODEL || OPENAI_MODEL_DEFAULTS.OPENAI_INVOICE_OCR_MODEL,
  }
}

export const openAIModelConfig = getOpenAIModelConfig()
